# Generated by Django 4.2.dev20230104104714 on 2023-03-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=500)),
                ('valeur_nutri', models.CharField(max_length=500)),
                ('process', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='static/totalement_food/images')),
            ],
        ),
    ]
