# Generated by Django 4.2.dev20230104104714 on 2023-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0003_alter_recette_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='photo',
            field=models.ImageField(upload_to='static/totalement_food/images/'),
        ),
    ]
