# Generated by Django 4.2.dev20230104104714 on 2023-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0005_alter_recette_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='banniere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='process',
            field=models.TextField(),
        ),
    ]
