# Generated by Django 4.2.dev20230104104714 on 2023-03-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0007_remove_recette_banniere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrees', models.CharField(max_length=200)),
                ('plats', models.CharField(max_length=200)),
                ('desserts', models.CharField(max_length=200)),
            ],
        ),
    ]
