# Generated by Django 4.2.dev20230104104714 on 2023-03-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0008_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='desserts',
            new_name='dessert',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='entrees',
            new_name='entree',
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='plats',
            new_name='plat',
        ),
    ]
