# Generated by Django 4.2.dev20230104104714 on 2023-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0009_rename_categories_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('definition', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
