# Generated by Django 4.2.dev20230104104714 on 2023-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0011_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lexique',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
