# Generated by Django 4.2.dev20230104104714 on 2023-03-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0012_categorie_definition_alter_lexique_definition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lexique',
        ),
    ]
