# Generated by Django 4.2.dev20230104104714 on 2023-03-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalement_food', '0013_delete_lexique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('energie', models.CharField(max_length=10)),
                ('proteine', models.CharField(max_length=10)),
                ('lipide', models.CharField(max_length=10)),
                ('glucide', models.CharField(max_length=10)),
            ],
        ),
    ]
